// Dactyl Manuform Hotswap
#pragma once

#include "config_common.h"
// Basic Config

//#define PRODUCT_ID 0x0002

#define SPLIT_POINTING_ENABLE
//#define ROTATIONAL_TRANSFORM_ANGLE  -25

#define SPLIT_TRANSACTION_IDS_KB RPC_ID_KB_CONFIG_SYNC

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1200
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200
#define CHARYBDIS_DRAGSCROLL_DPI 200

// End of Basic Config
